version: '3'
services: 
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./api/.env

  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - api
    env_file:
      - ./ui/.env
